packages = [
    "opencv-python",
    "numpy", 
    "pillow",
    "matplotlib"
]

[files]
"https://chrisrogers.pyscriptapps.com/talking-on-a-channel/latest/py/channel.py" = ""

[js_modules.main]
"https://chrisrogers.pyscriptapps.com/summer25-guts/latest/js/plotly.js" = "Plotly"
"https://chrisrogers.pyscriptapps.com/summer25-guts/latest/js/ble.js" = "ble"
"https://chrisrogers.pyscriptapps.com/summer25-guts/latest/js/files.js" = "files"
"https://cdn.jsdelivr.net/npm/micro-repl@0.8.2/serial.js" = "micro_repl"
